name: Daily Tech News Generation

on:
  schedule:
    # Run at 3 AM UTC (8 PM Pacific Time) every day
    - cron: '0 3 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-tech-news:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Set a reasonable timeout
    # Add permissions for the GITHUB_TOKEN
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Ensure directories exist
        run: |
          mkdir -p content/tech-news
          echo "Created content/tech-news directory"
          ls -la content/
          
      - name: Verify API key format
        run: |
          if [ -z "$PERPLEXITY_API_KEY" ]; then
            echo "Error: PERPLEXITY_API_KEY is not set"
            exit 1
          fi
          
          # Check if the API key has the expected format (without revealing it)
          KEY_LENGTH=${#PERPLEXITY_API_KEY}
          echo "API key length: $KEY_LENGTH characters"
          
          # Check if it starts with expected prefix (adjust if needed)
          if [[ $PERPLEXITY_API_KEY == pplx-* ]]; then
            echo "API key has the expected prefix format"
          else
            echo "Warning: API key does not start with the expected prefix 'pplx-'"
            echo "Please ensure you're using a valid Perplexity API key"
          fi
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        
      - name: Generate daily tech news
        id: generate_news
        run: |
          set -o pipefail
          node scripts/generate-daily-news.js 2>&1 | tee news_generation.log
          if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "::error::News generation failed. See log for details."
            cat news_generation.log
            exit 1
          fi
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          
      - name: Commit changes
        id: commit
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add content/tech-news/
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            git commit -m "Add daily tech news update"
            git push
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Trigger Netlify build
        if: steps.commit.outputs.has_changes == 'true'
        uses: netlify/actions/cli@master
        with:
          args: deploy --build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} 